properties([
  parameters([
    choice(
      name: 'Environment',
      choices: ['prod', 'stage'],
      description: 'Select the environment'
    ),
    [
      $class: 'CascadeChoiceParameter',
      choiceType: 'PT_SINGLE_SELECT',
      name: 'Host',
      description: 'Select the host',
      referencedParameters: 'Environment',
      script: [
        $class: 'GroovyScript',
        fallbackScript: [
          classpath: [],
          sandbox: true,
          script: 'return ["ERROR"]'
        ],
        script: [
          classpath: [],
          sandbox: true,
          script: '''
            switch(Environment) {
              case "prod":
                return ["HostA", "HostB"]
              case "stage":
                return ["HostC", "HostD"]
              default:
                return ["Select Environment first"]
            }
          '''
        ]
      ]
    ]
  ])
])

pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo "${params.Environment}"
        echo "${params.Host}"
      }
    }
  }
}
